import { useEffect, useRef, useState, useCallback } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { useTranslation } from '@/i18n';
import { useAppStore } from '@/store/useAppStore';
import { haptic } from '@/lib/haptic';
import { sfx } from '@/lib/audio';

/* ═══════════════════════════════════════════════════════════════════
   THE BOLT — lock screen.

   An S drawn as a lightning strike, traced ground → sky.

   The silhouette is a filled polygon whose width varies along the spine,
   generated by offsetting the centreline with a mitre limit of 2. That is
   where the points come from. The previous mark was a constant-width stroke,
   which reads as wire — which is why it needed arrow markers glued to its
   tips to fake the taper. There are no markers here and nothing to fake.

   Depth is built, not painted: the face, three extrusion steps and the cast
   shadow are separate layers at different translateZ inside one preserve-3d
   plate, so tilting parallaxes them against each other.

   You cannot fail. The corridor is wide, progress never falls back while you
   hold, and letting go early drains the charge instead of punishing you —
   the old screen fired a five-pulse error pattern for not drawing well.
   ═══════════════════════════════════════════════════════════════════ */

/** Outline: centreline [66,368]→[170,250]→[92,232]→[176,46], mitre 2. */
const BOLT_D =
  'M 68.3 370.0 L 223.9 232.7 L 130.2 213.1 L 178.7 47.2 L 173.3 44.8 L 53.8 250.9 L 116.1 267.3 L 63.7 366.0 Z';
/** The axis the charge travels, and the line the finger is measured against. */
const SPINE_D = 'M 66 368 L 170 250 L 92 232 L 176 46';

const SAMPLE = 96;
/** Corridor half-width in viewBox units. The bolt is ~120 wide: this is wide
    on purpose — a front door is not a dexterity test. */
const RAIL = 78;
/** How far ahead of the current position the finger may jump. */
const LOOKAHEAD = 26;
/** Grab radius around the ground terminal. */
const GRAB = 96;
const COMMIT = 0.9;
/** The one detent you feel on the way up. */
const ARM = 0.55;
const TILT = 11;
/** Charge drain on release. A duration, not a rate: integrating a rate with a
    clamped dt makes the animation run slower the slower the device is, and
    this page has a GPU simulation behind it. */
const DRAIN_MS = 420;

type Pt = { x: number; y: number };
const dist = (a: Pt, b: Pt) => Math.hypot(a.x - b.x, a.y - b.y);

export default function BootScreen() {
  const { t } = useTranslation();
  const setBooted = useAppStore((s) => s.setBooted);
  const theme = useAppStore((s) => s.theme);
  const reducedMotion = useAppStore((s) => s.reducedMotion);
  const skipLock =
    typeof window !== 'undefined' && new URLSearchParams(window.location.search).has('shot');
  const [done, setDone] = useState(skipLock);
  const [unlocked, setUnlocked] = useState(skipLock);

  const rootRef = useRef<HTMLDivElement>(null);
  const plateRef = useRef<HTMLDivElement>(null);
  const svgRef = useRef<SVGSVGElement>(null);
  const spineRef = useRef<SVGPathElement>(null);
  const chargeRef = useRef<SVGPathElement>(null);
  const sparkRef = useRef<SVGCircleElement>(null);

  const p = useRef(0);
  const cursor = useRef(0);
  const holding = useRef(false);
  const armed = useRef(false);
  const opening = useRef(false);
  const template = useRef<Pt[]>([]);
  const spineLen = useRef(0);
  const raf = useRef(0);
  const tiltRaf = useRef(0);
  const pendingTilt = useRef<{ x: number; y: number } | null>(null);

  /* ── Paint ───────────────────────────────────────────────────── */
  const paint = useCallback((v: number) => {
    p.current = v;
    const total = spineLen.current;
    if (chargeRef.current && total > 0) {
      chargeRef.current.style.strokeDasharray = String(total);
      chargeRef.current.style.strokeDashoffset = String(total * (1 - v));
    }
    plateRef.current?.style.setProperty('--p', String(v));
    rootRef.current?.style.setProperty('--p', String(v));

    const spine = spineRef.current;
    const spark = sparkRef.current;
    if (spine && spark) {
      const at = spine.getPointAtLength(spine.getTotalLength() * v);
      spark.setAttribute('cx', String(at.x));
      spark.setAttribute('cy', String(at.y));
    }
  }, []);

  /* ── Opening ─────────────────────────────────────────────────── */
  const open = useCallback(() => {
    if (opening.current) return;
    opening.current = true;
    holding.current = false;
    cancelAnimationFrame(raf.current);
    cursor.current = Math.max(0, template.current.length - 1);
    paint(1);
    setUnlocked(true);
    haptic('success');
    sfx.confirm();
    sfx.open();
    window.setTimeout(() => setBooted(true), 90);
    window.setTimeout(() => setDone(true), reducedMotion ? 340 : 1000);
  }, [paint, reducedMotion, setBooted]);

  /* ── Release: the charge drains. This is the whole failure story. ── */
  const drain = useCallback(() => {
    cancelAnimationFrame(raf.current);
    const from = p.current;
    const t0 = performance.now();
    const step = (now: number) => {
      const k = Math.min(1, (now - t0) / DRAIN_MS);
      // easeOutCubic — leaves quickly, settles softly, never slams shut.
      const next = from * (1 - (1 - Math.pow(1 - k, 3)));
      if (k >= 1) {
        cursor.current = 0;
        armed.current = false;
        paint(0);
        return;
      }
      cursor.current = Math.round(next * (template.current.length - 1));
      paint(next);
      raf.current = requestAnimationFrame(step);
    };
    raf.current = requestAnimationFrame(step);
  }, [paint]);

  /* ── Tilt ────────────────────────────────────────────────────── */
  const flushTilt = useCallback(() => {
    tiltRaf.current = 0;
    const v = pendingTilt.current;
    const plate = plateRef.current;
    if (!v || !plate) return;
    plate.style.setProperty('--ty', `${v.x * TILT}deg`);
    plate.style.setProperty('--tx', `${-v.y * TILT}deg`);
  }, []);

  const aimTilt = useCallback(
    (clientX: number, clientY: number) => {
      if (reducedMotion) return;
      const r = rootRef.current?.getBoundingClientRect();
      if (!r) return;
      pendingTilt.current = {
        x: ((clientX - r.left) / r.width - 0.5) * 2,
        y: ((clientY - r.top) / r.height - 0.5) * 2,
      };
      if (!tiltRaf.current) tiltRaf.current = requestAnimationFrame(flushTilt);
    },
    [flushTilt, reducedMotion],
  );

  /* ── Geometry ────────────────────────────────────────────────── */
  const toSvg = useCallback((clientX: number, clientY: number): Pt | null => {
    const svg = svgRef.current;
    if (!svg) return null;
    const ctm = svg.getScreenCTM();
    if (!ctm) return null;
    const pt = svg.createSVGPoint();
    pt.x = clientX;
    pt.y = clientY;
    const q = pt.matrixTransform(ctm.inverse());
    return { x: q.x, y: q.y };
  }, []);

  /** Monotonic. Outside the corridor the charge HOLDS — it never falls back
      under the finger, which is what made the old screen feel like a test. */
  const advance = useCallback((at: Pt): number => {
    const tpl = template.current;
    if (tpl.length < 2) return 0;
    let best = RAIL + 1;
    let bestI = cursor.current;
    for (let k = 0; k <= LOOKAHEAD; k++) {
      const j = cursor.current + k;
      if (j >= tpl.length) break;
      const d = dist(at, tpl[j]);
      if (d < best) {
        best = d;
        bestI = j;
      }
    }
    if (best > RAIL) return cursor.current / (tpl.length - 1);
    cursor.current = Math.max(cursor.current, bestI);
    return cursor.current / (tpl.length - 1);
  }, []);

  /* ── Pointer ─────────────────────────────────────────────────── */
  const onDown = useCallback(
    (e: React.PointerEvent) => {
      if (opening.current) return;
      if (reducedMotion) {
        open();
        return;
      }
      aimTilt(e.clientX, e.clientY);
      const at = toSvg(e.clientX, e.clientY);
      if (!at || template.current.length === 0) return;
      if (dist(at, template.current[0]) > GRAB) {
        // Away from the striking point: pulse the mark instead of a message.
        plateRef.current?.setAttribute('data-hint', '');
        window.setTimeout(() => plateRef.current?.removeAttribute('data-hint'), 620);
        haptic('light');
        return;
      }
      cancelAnimationFrame(raf.current);
      holding.current = true;
      armed.current = false;
      cursor.current = 0;
      plateRef.current?.setAttribute('data-holding', '');
      (e.currentTarget as HTMLElement).setPointerCapture?.(e.pointerId);
      paint(0);
      haptic('light');
      sfx.hover();
    },
    [aimTilt, open, paint, reducedMotion, toSvg],
  );

  const onMove = useCallback(
    (e: React.PointerEvent) => {
      if (opening.current) return;
      aimTilt(e.clientX, e.clientY);
      if (!holding.current) return;
      const at = toSvg(e.clientX, e.clientY);
      if (!at) return;
      const v = advance(at);
      paint(v);
      if (!armed.current && v >= ARM) {
        armed.current = true;
        haptic('light');
        sfx.hover();
      }
      if (v >= COMMIT) open();
    },
    [advance, aimTilt, open, paint, toSvg],
  );

  const onUp = useCallback(() => {
    if (!holding.current || opening.current) return;
    holding.current = false;
    plateRef.current?.removeAttribute('data-holding');
    if (p.current >= COMMIT) open();
    else drain();
  }, [drain, open]);

  const onLeave = useCallback(() => {
    if (reducedMotion) return;
    pendingTilt.current = { x: 0, y: 0 };
    if (!tiltRaf.current) tiltRaf.current = requestAnimationFrame(flushTilt);
  }, [flushTilt, reducedMotion]);

  const onKey = useCallback(
    (e: React.KeyboardEvent) => {
      if (opening.current) return;
      if (e.key === 'Enter' || e.key === ' ') {
        e.preventDefault();
        open();
      }
    },
    [open],
  );

  /* ── Lifecycle ───────────────────────────────────────────────── */
  useEffect(() => {
    if (!skipLock) return;
    localStorage.setItem('hkmodd-theme', 'default');
    document.documentElement.removeAttribute('data-theme');
    document.querySelector('.app-root')?.removeAttribute('data-theme');
    useAppStore.setState({ theme: 'default', booted: true });
  }, [skipLock]);

  useEffect(() => {
    const html = document.documentElement;
    const body = document.body;
    if (done) {
      window.scrollTo({ top: 0, left: 0, behavior: 'instant' });
      html.style.overflow = '';
      body.style.overflow = '';
      html.style.height = '';
      body.style.height = '';
      return;
    }
    html.style.overflow = 'hidden';
    body.style.overflow = 'hidden';
    html.style.height = '100%';
    body.style.height = '100%';
  }, [done]);

  useEffect(() => {
    if (done) return;
    const spine = spineRef.current;
    if (spine) {
      const total = spine.getTotalLength();
      spineLen.current = total;
      const out: Pt[] = [];
      for (let i = 0; i <= SAMPLE; i++) {
        const q = spine.getPointAtLength((total * i) / SAMPLE);
        out.push({ x: q.x, y: q.y });
      }
      template.current = out;
    }
    paint(0);
    return () => {
      cancelAnimationFrame(raf.current);
      cancelAnimationFrame(tiltRaf.current);
    };
  }, [done, paint]);

  const hint = reducedMotion ? t.boot.hintTap : t.boot.hint;

  /* Extrusion steps, back to front. Separate layers so they parallax. */
  const EXTRUDE = [-22, -15, -8];

  return (
    <AnimatePresence>
      {!done && (
        <motion.div
          ref={rootRef}
          className={`lock${unlocked ? ' is-unlocking' : ''}`}
          data-theme={theme !== 'default' ? theme : undefined}
          exit={{ opacity: 0 }}
          transition={{ duration: 0.3, ease: [0.16, 1, 0.3, 1] }}
          onPointerDown={onDown}
          onPointerMove={onMove}
          onPointerUp={onUp}
          onPointerCancel={onUp}
          onPointerLeave={onLeave}
        >
          <div className="lock__field" aria-hidden />
          <div className="lock__grain" aria-hidden />

          <div ref={plateRef} className="lock__plate">
            <div
              className="lock__stage"
              role="button"
              tabIndex={0}
              aria-label={hint}
              onKeyDown={onKey}
            >
              {/* cast shadow — furthest back, so it slides most under tilt */}
              <div className="lock__layer lock__cast" aria-hidden>
                <svg viewBox="0 0 240 400"><path d={BOLT_D} /></svg>
              </div>

              {/* extrusion body */}
              {EXTRUDE.map((z, i) => (
                <div
                  key={z}
                  className="lock__layer lock__extrude"
                  style={{ '--z': `${z}px`, '--i': i } as React.CSSProperties}
                  aria-hidden
                >
                  <svg viewBox="0 0 240 400"><path d={BOLT_D} /></svg>
                </div>
              ))}

              {/* face + charge + spark */}
              <div className="lock__layer lock__face">
                <svg ref={svgRef} viewBox="0 0 240 400" aria-hidden>
                  <defs>
                    {/* userSpaceOnUse so the ramp is anchored to the mark, not
                        to whatever bounding box the stroke happens to have. */}
                    <linearGradient
                      id="boltHot"
                      gradientUnits="userSpaceOnUse"
                      x1="54"
                      y1="370"
                      x2="224"
                      y2="45"
                    >
                      <stop className="lock__stop-a" offset="0%" />
                      <stop className="lock__stop-b" offset="52%" />
                      <stop className="lock__stop-c" offset="100%" />
                    </linearGradient>
                    {/* A clip, not a mask. The charge used to be a dashed
                        stroke inside a <mask>: Chrome re-rasterises a masked
                        SVG when the plate's 3D transform changes and rebuilt
                        that dash wrongly, lighting the bolt in bands at rest
                        until some unrelated DOM read forced a flush. Neither
                        rendering the dash as an attribute nor dropping
                        pathLength for real user units fixed it. Here the clip
                        is static geometry and the dash lives on an ordinary
                        painted stroke, so there is nothing to recompute. */}
                    <clipPath id="boltClip">
                      <path d={BOLT_D} />
                    </clipPath>
                  </defs>

                  <path className="lock__bolt-cold" d={BOLT_D} />
                  <g className="lock__bolt-hot" clipPath="url(#boltClip)">
                    <path
                      ref={chargeRef}
                      d={SPINE_D}
                      fill="none"
                      /* Just wide enough to cover the mark: the outline sits
                         at most 58 units off the spine (half-width 29, mitre
                         2), so 150 covers it with 17 to spare. Wider than
                         that and the round join floods well past the traced
                         point at each kink, and the light outruns the spark. */
                      strokeWidth="150"
                      strokeLinecap="butt"
                      strokeLinejoin="round"
                      strokeDasharray="10000"
                      strokeDashoffset="10000"
                    />
                  </g>
                  <path className="lock__bolt-rim" d={BOLT_D} />
                  <path
                    ref={spineRef}
                    d={SPINE_D}
                    fill="none"
                    stroke="none"
                    pointerEvents="none"
                  />
                  <circle ref={sparkRef} className="lock__spark" r="7" cx="66" cy="368" />
                </svg>
              </div>
            </div>
          </div>

          <p className="lock__hint">{unlocked ? '' : hint}</p>
        </motion.div>
      )}
    </AnimatePresence>
  );
}
